import org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency

plugins {
    id 'fabric-loom' version '1.10-SNAPSHOT'
    id 'maven-publish'
    id 'com.gradleup.shadow' version '8.3.6'
    id 'java-library'
    id "com.peterabeles.gversion" version "1.10.3"
    id "com.modrinth.minotaur" version "2+"
}

gversion {
  srcDir = "src/main/java/"
  classPackage = "com.javazilla.bukkitfabric"
  className = "GitVersion"
}
project.compileJava.dependsOn(createVersionFile)

sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

configurations { 
    extraLibs
    removeLibs
    metest
}


loom {
    accessWidenerPath = file("src/main/resources/bukkitfabric.accesswidener")
}

repositories {

    maven { url = 'https://jitpack.io' }
    maven { url = 'https://repo.codemc.io/repository/maven-releases/' }
	maven { url = 'https://repo.spongepowered.org/maven' }
	maven { url = 'https://repo.papermc.io/repository/maven-public/' }
	maven { url = 'https://maven.izzel.io/releases' }
    mavenCentral()
}

configurations.all {
    // Check for updates every build
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

// Paper-API
def PAPER_VER_A = "1.21.4-R0.1-SNAPSHOT"
// def PAPER_VER_B = "1.21.4-R0.1-20250313.115134-207"
//paper-api-1.21.4-R0.1-20250511.205801-225
def PAPER_VER_B = "1.21.4-R0.1-20250511.205801-225"

def PAPER_API_VER = "io.papermc.paper:paper-api:" + PAPER_VER_B

// def jarUrl = String.format("%s%s/%s/%s/%s-%s.jar", url.toString(), dep.group.replace('.', '/'), dep.name, dep.version, dep.name, dep.version)
// io/papermc/paper/paper-api/1.21.4-R0.1-SNAPSHOT/paper-api-1.21.4-R0.1-20250313.115134-207.jar

dependencies {
    minecraft("com.mojang:minecraft:${project.minecraft_version}") {
    	exclude module: 'commons-logging'
    }
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation("net.fabricmc:fabric-loader:${project.loader_version}")
    // modImplementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_version}")
    
    // Make a collection of all api modules we wish to use
    Set<String> apiModules = [
    	"fabric-api-base",
    	"fabric-networking-api-v1",
    	"fabric-screen-handler-api-v1"
    ]

    DefaultExternalModuleDependency ic = new DefaultExternalModuleDependency("com.javazilla.mods", "icommon-fabric-1.21.4", "1.21.4", null)
    ic.setChanging(true) // Make sure we get the latest version of iCommon

    //include(modImplementation(ic))
    modImplementation(ic)
    
    //modImplementation( project(':iCommon-API') )
    //include( project(':iCommon-API') )

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modImplementation fileTree(dir: 'libs', include: 'MohistRemapper-0.3-1.20.x.jar')
    extraLibs fileTree(dir: 'libs', include: 'MohistRemapper-0.3-1.20.x.jar')
	
	modImplementation "io.izzel:tools:1.3.0"
    extraLibs "io.izzel:tools:1.3.0"

    extraLibs fileTree(dir: 'libs', include: 'commons-lang-2.6.jar')
    // extraLibs fileTree(dir: 'libs', include: 'adventure.jar')
    extraLibs fileTree(dir: 'libs', include: 'adventure-exam.jar')
    //extraLibs group: "org.jetbrains", name: "annotations", version: "20.1.0"
    extraLibs group: "com.googlecode.json-simple", name: "json-simple", version: "1.1.1"

    extraLibs("org.yaml:snakeyaml:1.33")

    // 
    //compileOnly fileTree(dir: 'libs', include: "${project.paper_jar}")
    
	// Paper-API
	// compileOnly("io.papermc.paper:paper-api:1.19.4-R0.1-20230608.201059-104")
	// compileOnly("io.papermc.paper:paper-api:1.20.1-R0.1-20230921.165944-178")
	
	//compileOnly("io.papermc.paper:paper-api:1.20.2-R0.1-20231203.034718-122")
	// compileOnly("io.papermc.paper:paper-api:1.20.3-R0.1-20231207.043048-3")
	// compileOnly("io.papermc.paper:paper-api:1.20.4-R0.1-20240528.102248-175")
	//compileOnly platform("io.papermc.paper:paper-api:1.20.5-R0.1-20240429.035133-20") {
	//	exclude group: "net.kyori", module: "adventure-bom"
	//}
	
	// compileOnly("io.papermc.paper:paper-api:1.20.6-R0.1-20240916.192025-126")
	//compileOnly("io.papermc.paper:paper-api:1.21.1-R0.1-20240810.105324-1")
	// compileOnly("io.papermc.paper:paper-api:1.21.1-R0.1-20241021.162528-124")
	// compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-20241215.095037-18")
	// compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-20241223.153548-25")
	// compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-20241223.235543-30")
	// compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-20241226.084728-40")
	// compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-20250118.134032-116")
	// compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-20241223.153548-25")
	// compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-20241223.153548-25")
	

	// Paper-API libs
	// compileOnly
	// modImplementation("io.papermc.paper:paper-api:1.21.4-R0.1-20250118.134032-116")
	// modImplementation("io.papermc.paper:paper-api:1.21.4-R0.1-20250303.170158-184")
	// modImplementation("io.papermc.paper:paper-api:1.21.4-R0.1-20250313.115134-207")
	modImplementation(PAPER_API_VER)
	modImplementation("net.md-5:bungeecord-chat:1.16-R0.4")
	modImplementation("net.kyori:adventure-api:4.18.0")
	modImplementation("net.kyori:adventure-text-serializer-gson:4.18.0")
	modImplementation("net.kyori:adventure-text-serializer-legacy:4.18.0")
	modImplementation("net.kyori:adventure-text-serializer-plain:4.18.0")
	modImplementation("net.kyori:adventure-text-minimessage:4.18.0")

	//extraLibs fileTree(dir: 'libs', include: "${project.paper_jar}")
    compileOnly fileTree(dir: 'libs', include: 'commons-lang-2.6.jar')
    //compileOnly fileTree(dir: 'libs', include: 'slf4j.jar')
    compileOnly group: "org.jetbrains", name: "annotations", version: "18.0.0"
    compileOnly group: "com.googlecode.json-simple", name: "json-simple", version: "1.1.1"

	compileOnly "io.leangen.geantyref:geantyref:1.3.16"
	include(modImplementation("io.leangen.geantyref:geantyref:1.3.16"))

    //compileOnly 'net.fabricmc:tiny-mappings-parser:0.2.2.14'
	//compileOnly 'net.fabricmc:tiny-remapper:0.4.2'
	//compileOnly 'net.fabricmc:access-widener:1.0.0'

    // NMS Remapping
    // srglib-0.1.2.jar
    extraLibs fileTree(dir: 'libs', include: "srglib-0.1.2.jar")
    include(modImplementation("net.md-5:SpecialSource:1.11.2"))

    compileOnly fileTree(dir: 'libs', include: "srglib-0.1.2.jar")

    // (Optional) Fabric Permissions API.
    // modImplementation "com.javazilla.mods:permissions:1.1"

    // Remove parts that are included with Minecraft or Downloaded
    removeLibs group: "com.google.guava", name: "guava", version: "21.0"
    removeLibs group: 'org.apache.commons', name: 'commons-lang3', version: '3.8.1'
    removeLibs group: 'org.apache.commons', name: 'commons-collections4', version: '4.2'
    removeLibs group: 'commons-collections', name: 'commons-collections', version: '3.2.2'
    removeLibs group: 'commons-lang', name: 'commons-lang', version: '2.6'
    removeLibs group: 'commons-logging', name: 'commons-logging', version: '1.2'
    removeLibs group: 'com.google.code.gson', name: 'gson', version: '2.8.6'
    removeLibs group: 'junit', name: 'junit', version: '4.10'

    configurations.api.extendsFrom( (configurations.extraLibs) )

   //  annotationProcessor 'com.github.bsideup.jabel:jabel-javac-plugin:0.4.1'
   
 	// TODO:
   	// annotationProcessor("com.pkware.jabel:jabel-javac-plugin:1.0.1-1")
    compileOnly("com.pkware.jabel:jabel-javac-plugin:1.0.1-1")
}

configurations.implementation {
    exclude group: 'commons-logging', module: 'commons-logging'
}

configure([tasks.compileJava]) {
    sourceCompatibility = 21//16 // for the IDE support
    options.release = 21//16

    javaCompiler = javaToolchains.compilerFor {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

processResources {
    inputs.property "version", project.version

	duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from(sourceSets.main.resources.srcDirs) {
        include "fabric.mod.json"
        if(System.env.BUILD_NUMBER){
            expand "version": System.env.BUILD_NUMBER
        }
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude "fabric.mod.json"
    }
}

tasks.withType(JavaCompile) {
	options.encoding = "UTF-8"
	options.deprecation = false
	options.compilerArgs << '-Xlint:-deprecation'
	options.compilerArgs << '-Xlint:-removal'
	options.compilerArgs << '-Xlint:-dep-ann'
	options.compilerArgs << '-XDignore.symbol.file'
	
	println(options.compilerArgs)
}

jar {
	duplicatesStrategy = DuplicatesStrategy.WARN
    from "LICENSE"
    from {
        (configurations.extraLibs - configurations.removeLibs).filter{ it.exists() }.collect { it.isDirectory() ? it : zipTree(it) }
    }
    exclude("**/mojang-translations/")
	// exclude("*.jar") // WHY GRADLE, WHY?
}

shadowJar {
    configurations = [project.configurations.api]
    dependencies {
      exclude(dependency('com.mojang:minecraft:*'))
      exclude(dependency('org.objectweb:asm:*'))
      exclude(dependency('com.google.guava:guava:*'))
    }
}

/*task publishModrinth (type: TaskModrinthUpload){ // Make sure it runs after build!
    onlyIf {
        System.getenv("MODRINTH") // Only attempt to run this task if the MODRINTH variable is set, otherwise SKIP it
    }

    token = System.getenv("MODRINTH") // An environment property called MODRINTH that is your token, set via Gradle CLI, GitHub Actions, Idea Run Configuration, or other
    projectId = 'MLYQ9VGP'
    versionType = VersionType.BETA
    versionNumber = '1.17-' + System.env.BUILD_NUMBER // Will fail if Modrinth has this version already
    versionName = '#' + System.env.BUILD_NUMBER + ' (1.19.2)'
    // On fabric, use 'remapJar' instead of 'jar'
    uploadFile = remapJar // This is the java jar task. If it can't find the jar, try 'jar.outputs.getFiles().asPath' in place of 'jar' 
    addGameVersion('1.19.2') // Call this multiple times to add multiple game versions. There are tools that can help you generate the list of versions
    // addGameVersion('1.18')
    addLoader('fabric')
}*/

modrinth {
    token = System.getenv("MODRINTH") // This is the default. Remember to have the MODRINTH_TOKEN environment variable set or else this will fail, or set it to whatever you want - just make sure it stays private!
    projectId = "MLYQ9VGP" // This can be the project ID or the slug. Either will work!
    versionNumber = "1.21.4-" + System.env.BUILD_NUMBER // You don't need to set this manually. Will fail if Modrinth has this version already
    versionType = "beta" // This is the default -- can also be `beta` or `alpha`
    uploadFile = remapJar // With Loom, this MUST be set to `remapJar` instead of `jar`!
    gameVersions = ["1.21.4"] // Must be an array, even with only one version
    loaders = ["fabric"] // Must also be an array - no need to specify this if you're using Loom or ForgeGradle
}


ext.getURLofDependencyArtifact = {
	project.configurations.modImplementation.dependencies.each { dep ->
		if (dep.name.contains('paper')) {
			println(dep.name)
			println(dep)
			def urls = [
				'https://repo.papermc.io/repository/maven-snapshots/',
				'https://repo.codemc.io/repository/nms-local/',
				'https://repo.codemc.io/repository/maven-releases/'
			]

			for (String url : urls) {
				def jarUrl = String.format("%s%s/%s/%s/%s-%s.jar", url.toString(), dep.group.replace('.', '/'), dep.name, dep.version, dep.name, dep.version)
				try {
					def jarfile = new URL(jarUrl)
					def inStream = jarfile.openStream();
					if (inStream != null) {
						println(String.format("%s:%s:%s", dep.group, dep.name, dep.version) + " -> " + jarUrl)
						return jarUrl
					}
				} catch (Exception ignored) {
				}
			}
		}
	}
}

ext.downloadPaperFile = {
//    def fileURL = new URL("https://repo.papermc.io/repository/maven-snapshots/io/papermc/paper/paper-api/" + PAPER_VER_A +"/paper-api-" + PAPER_VER_B + ".jar")
    def fileURL = new URL("https://web.archive.org/web/20250518123011/https://repo.papermc.io/repository/maven-snapshots/io/papermc/paper/paper-api/1.21.4-R0.1-SNAPSHOT/paper-api-1.21.4-R0.1-20250511.205801-225.jar")
    def localFile = file("repos/tempp/paper-api-" + PAPER_VER_B + ".jar")

    localFile.getParentFile().mkdirs()
    fileURL.withInputStream { i ->
		localFile.withOutputStream { o ->
			o << i
		}
    }
}

// Make sure paper-api on the repo is kept updated.
publishing {
	configurations.api.setCanBeResolved(true)
	downloadPaperFile()
    publications {
        mavenJava(MavenPublication) {
			groupId = 'io.papermc.paper'
            artifactId = PAPER_VER_A
			version = PAPER_VER_B
			artifact file("repos/tempp/paper-api-" + PAPER_VER_B + ".jar")
        }
    }
    repositories {
        maven {
            // change URLs to point to your repos, e.g. http://my.org/repo
            def releasesRepoUrl = layout.buildDirectory.dir('repos/releases')
            def snapshotsRepoUrl = layout.buildDirectory.dir('repos/snapshots')
            url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
        }
    }
}
