# Use 1GB of RAM
#
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
    # check these on https://modmuss50.me/fabric.html

	# 1.21.8
	# minecraft_version=1.21.8
	# yarn_mappings=1.21.8+build.1
	# loader_version=0.17.2
	# fabric_version=0.133.4+1.21.8

	# 1.21.10
	# minecraft_version=1.21.10
	# yarn_mappings=1.21.10+build.2
	# loader_version=0.17.3
	# fabric_version=0.136.0+1.21.10
	
	# 1.21.11
	# minecraft_version=1.21.11_unobfuscated
	#loader_version=0.18.4
	# fabric_version=0.141.3+1.21.11
	# fabric_version=0.139.4+1.21.11_unobfuscated
	
	# 26.1.2
	# minecraft_version=26.1.2
	# loader_version=0.19.2
	# fabric_version=0.149.1+26.1.2

	# 26.2
	minecraft_version=26.2
	loader_version=0.19.3
	fabric_version=0.156.0+26.2

# Mod Properties
    mod_version = 26.2
    maven_group = org.cardboardpowered
    archives_base_name = Cardboard

# Paper API
	#paper_jar = paper-api-1.17-test.jar
	# Value not used; See build.gradle
	paper_jar = paper-api-1.19.4-550.jar
